//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBM.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBM.Core.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemler.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ekle.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükseklik Tipi.
        /// </summary>
        public static string AltitudeType {
            get {
                return ResourceManager.GetString("AltitudeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açı Tipi.
        /// </summary>
        public static string AngleType {
            get {
                return ResourceManager.GetString("AngleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emin misin?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat!.
        /// </summary>
        public static string Attentive {
            get {
                return ResourceManager.GetString("Attentive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksen.
        /// </summary>
        public static string Axis {
            get {
                return ResourceManager.GetString("Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksen Sırası.
        /// </summary>
        public static string AxisOrder {
            get {
                return ResourceManager.GetString("AxisOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Atıldı!.
        /// </summary>
        public static string BallThrown {
            get {
                return ResourceManager.GetString("BallThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale.
        /// </summary>
        public static string Castle {
            get {
                return ResourceManager.GetString("Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 1.
        /// </summary>
        public static string Castle1 {
            get {
                return ResourceManager.GetString("Castle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 2.
        /// </summary>
        public static string Castle2 {
            get {
                return ResourceManager.GetString("Castle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 3.
        /// </summary>
        public static string Castle3 {
            get {
                return ResourceManager.GetString("Castle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 4.
        /// </summary>
        public static string Castle4 {
            get {
                return ResourceManager.GetString("Castle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 5.
        /// </summary>
        public static string Castle5 {
            get {
                return ResourceManager.GetString("Castle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 6.
        /// </summary>
        public static string Castle6 {
            get {
                return ResourceManager.GetString("Castle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 7.
        /// </summary>
        public static string Castle7 {
            get {
                return ResourceManager.GetString("Castle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 8.
        /// </summary>
        public static string Castle8 {
            get {
                return ResourceManager.GetString("Castle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale 9.
        /// </summary>
        public static string Castle9 {
            get {
                return ResourceManager.GetString("Castle9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale Lazer Tablosu.
        /// </summary>
        public static string CastleLaserTable {
            get {
                return ResourceManager.GetString("CastleLaserTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale Ldr Konumları.
        /// </summary>
        public static string CastleLdrPoint {
            get {
                return ResourceManager.GetString("CastleLdrPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale No.
        /// </summary>
        public static string CastleNo {
            get {
                return ResourceManager.GetString("CastleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kale Pozisyonu.
        /// </summary>
        public static string CastlePosition {
            get {
                return ResourceManager.GetString("CastlePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyuncu ve antreman seçimi.
        /// </summary>
        public static string ChooseTrainingAndPlayer {
            get {
                return ResourceManager.GetString("ChooseTrainingAndPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başakşehir FK.
        /// </summary>
        public static string ClubName {
            get {
                return ResourceManager.GetString("ClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantılar.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 1.
        /// </summary>
        public static string Data1 {
            get {
                return ResourceManager.GetString("Data1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 10.
        /// </summary>
        public static string Data10 {
            get {
                return ResourceManager.GetString("Data10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri11.
        /// </summary>
        public static string Data11 {
            get {
                return ResourceManager.GetString("Data11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri12.
        /// </summary>
        public static string Data12 {
            get {
                return ResourceManager.GetString("Data12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 13.
        /// </summary>
        public static string Data13 {
            get {
                return ResourceManager.GetString("Data13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 2.
        /// </summary>
        public static string Data2 {
            get {
                return ResourceManager.GetString("Data2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 3.
        /// </summary>
        public static string Data3 {
            get {
                return ResourceManager.GetString("Data3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 4.
        /// </summary>
        public static string Data4 {
            get {
                return ResourceManager.GetString("Data4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 5.
        /// </summary>
        public static string Data5 {
            get {
                return ResourceManager.GetString("Data5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 6.
        /// </summary>
        public static string Data6 {
            get {
                return ResourceManager.GetString("Data6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 7.
        /// </summary>
        public static string Data7 {
            get {
                return ResourceManager.GetString("Data7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 8.
        /// </summary>
        public static string Data8 {
            get {
                return ResourceManager.GetString("Data8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri 9.
        /// </summary>
        public static string Data9 {
            get {
                return ResourceManager.GetString("Data9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri tekrar geri getirilemez!.
        /// </summary>
        public static string DataCanBeLost {
            get {
                return ResourceManager.GetString("DataCanBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri İşlemleri.
        /// </summary>
        public static string DataManage {
            get {
                return ResourceManager.GetString("DataManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme Başarısız.
        /// </summary>
        public static string DeleteUnSuccess {
            get {
                return ResourceManager.GetString("DeleteUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Desctription {
            get {
                return ResourceManager.GetString("Desctription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirme Linki.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Noktası.
        /// </summary>
        public static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarısız!.
        /// </summary>
        public static string ErrorActionUnsuccess {
            get {
                return ResourceManager.GetString("ErrorActionUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme işlemi başarısız!.
        /// </summary>
        public static string ErrorAdd {
            get {
                return ResourceManager.GetString("ErrorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi başarısız!.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme işlemi başarısız!.
        /// </summary>
        public static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futbolmatik.
        /// </summary>
        public static string FBM {
            get {
                return ResourceManager.GetString("FBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gol Oranı.
        /// </summary>
        public static string GoalStatus {
            get {
                return ResourceManager.GetString("GoalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gol Başarılı!.
        /// </summary>
        public static string GoalSuccess {
            get {
                return ResourceManager.GetString("GoalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gol Başarısız!.
        /// </summary>
        public static string GoalUnSuccess {
            get {
                return ResourceManager.GetString("GoalUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik.
        /// </summary>
        public static string Grafic {
            get {
                return ResourceManager.GetString("Grafic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra.
        /// </summary>
        public static string IdentityNo {
            get {
                return ResourceManager.GetString("IdentityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarı Durumu.
        /// </summary>
        public static string isSuccess {
            get {
                return ResourceManager.GetString("isSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string labelForDesctription {
            get {
                return ResourceManager.GetString("labelForDesctription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string labelForName {
            get {
                return ResourceManager.GetString("labelForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazer Adeti.
        /// </summary>
        public static string LaserCount {
            get {
                return ResourceManager.GetString("LaserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDR.
        /// </summary>
        public static string Ldr {
            get {
                return ResourceManager.GetString("Ldr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünite Numarası.
        /// </summary>
        public static string LdrUnitNo {
            get {
                return ResourceManager.GetString("LdrUnitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canlı.
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor 1 Durum.
        /// </summary>
        public static string Motor1State {
            get {
                return ResourceManager.GetString("Motor1State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor 2 Durum.
        /// </summary>
        public static string Motor2State {
            get {
                return ResourceManager.GetString("Motor2State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol Motor Hız.
        /// </summary>
        public static string MotorLeftSpeed {
            get {
                return ResourceManager.GetString("MotorLeftSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sağ Motor Hız.
        /// </summary>
        public static string MotorRightSpeed {
            get {
                return ResourceManager.GetString("MotorRightSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme işlemi başarılı..
        /// </summary>
        public static string MsgAdd {
            get {
                return ResourceManager.GetString("MsgAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi başarılı..
        /// </summary>
        public static string MsgDelete {
            get {
                return ResourceManager.GetString("MsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme işlemi başarılı..
        /// </summary>
        public static string MsgUpdate {
            get {
                return ResourceManager.GetString("MsgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Antreman Başlıyor!.
        /// </summary>
        public static string NewTrainingStarting {
            get {
                return ResourceManager.GetString("NewTrainingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır!.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterilecek kayıt bulunamadı.
        /// </summary>
        public static string NoRowsToShow {
            get {
                return ResourceManager.GetString("NoRowsToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şimdi Değil!.
        /// </summary>
        public static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyuncu.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyuncu Antremanı.
        /// </summary>
        public static string PlayerTraining {
            get {
                return ResourceManager.GetString("PlayerTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki Sayfa.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışan Antreaman Mevcut.
        /// </summary>
        public static string ProgressRun {
            get {
                return ResourceManager.GetString("ProgressRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla ?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız Puanı.
        /// </summary>
        public static string SpeedScore {
            get {
                return ResourceManager.GetString("SpeedScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skor Hız Çarpanı.
        /// </summary>
        public static string SpeedScoreFactor {
            get {
                return ResourceManager.GetString("SpeedScoreFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başla!.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Noktası.
        /// </summary>
        public static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antremana Başla.
        /// </summary>
        public static string StartTraining {
            get {
                return ResourceManager.GetString("StartTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon No.
        /// </summary>
        public static string StationNo {
            get {
                return ResourceManager.GetString("StationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Fırlatma.
        /// </summary>
        public static string ThrowBall {
            get {
                return ResourceManager.GetString("ThrowBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fırlatma Yüksekliği.
        /// </summary>
        public static string ThrowBallAltitude {
            get {
                return ResourceManager.GetString("ThrowBallAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fırlatma Açısı.
        /// </summary>
        public static string ThrowBallAngle {
            get {
                return ResourceManager.GetString("ThrowBallAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fırlatma.
        /// </summary>
        public static string Throwing {
            get {
                return ResourceManager.GetString("Throwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atış Adeti.
        /// </summary>
        public static string ThrowingCount {
            get {
                return ResourceManager.GetString("ThrowingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaman Aşımı Süresi.
        /// </summary>
        public static string ThrowTimeOut {
            get {
                return ResourceManager.GetString("ThrowTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fırlatma Bekleme Süresi.
        /// </summary>
        public static string ThrowWaitingTime {
            get {
                return ResourceManager.GetString("ThrowWaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süre.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaman Puanı.
        /// </summary>
        public static string TimeScore {
            get {
                return ResourceManager.GetString("TimeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skor Zaman Çarpanı.
        /// </summary>
        public static string TimeScoreFactor {
            get {
                return ResourceManager.GetString("TimeScoreFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saniye icinde sayfa yenilencek!.
        /// </summary>
        public static string ToRefresh {
            get {
                return ResourceManager.GetString("ToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antreman.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antreman Tarihi.
        /// </summary>
        public static string TrainingDate {
            get {
                return ResourceManager.GetString("TrainingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antreman Başlıyor!.
        /// </summary>
        public static string TrainingStarting {
            get {
                return ResourceManager.GetString("TrainingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antreman Kaydı.
        /// </summary>
        public static string TrainLog {
            get {
                return ResourceManager.GetString("TrainLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duvar Yönü.
        /// </summary>
        public static string WallPosition {
            get {
                return ResourceManager.GetString("WallPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzle!.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sende İzle.
        /// </summary>
        public static string WatchToo {
            get {
                return ResourceManager.GetString("WatchToo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antreman İzle.
        /// </summary>
        public static string WatchTraining {
            get {
                return ResourceManager.GetString("WatchTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet Sil!.
        /// </summary>
        public static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
    }
}
